//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Opten.Excel")]
[assembly: AssemblyDescription("Opten.Excel")]
[assembly: AssemblyCompany("OPTEN AG")]
[assembly: AssemblyProduct("Opten.Excel")]
[assembly: AssemblyCopyright("Copyright (c) 2015 - 2019 OPTEN AG")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyConfiguration("")]
[assembly: Guid("43d3d4d6-1c33-4c37-a290-07efec35739e")]
[assembly: ComVisible(false)]

